[[ $- != *i* ]] && return

if [ -f /etc/bashrc ]; then
				. /etc/bashrc
fi

if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
				PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

alias ls='ls --color --classify --human-readable'
alias ll='ls -l'
alias ll.='ls -la'
alias lls='ls -la --sort-size'
alias llt='ls -la --sort-time'

alias update='yay -Syyu'
alias upgrade='yay -Syu; flatpak update'
alias install='yay -S'
alias remove='yay -Rns'
alias search='yay'
alias clean='sudo paccache -rk1 && yay -Sc && yay -Rns $(pacman -Qtdq)'
alias rebuild="yay -S $(pacman -Qm | awk '{ print $1 }')"

alias ikey='gpg --keyserver keyserver.ubuntu.com --recv'
alias cp='/bin/cp -i'
alias mv='/bin/mv -i'
alias rm='/bin/rm -i'
alias mksrcinfo='makepkg --printsrcinfo > .SRCINFO'

PS1='\W > '

export EDITOR='vim'
export VISUAL='vim'
export MAKEFLAGS="-j$(nproc)"

if [ -f /usr/lib/bash-git-prompt/gitprompt.sh ]; then
				GIT_PROMPT_ONLY_IN_REPO=1
				GIT_PROMPT_THEME=Default_Arch
				GIT_PROMPT_END_USER=" \n\W > "
				source /usr/lib/bash-git-prompt/gitprompt.sh
fi

[[ $PS1 && -f /usr/share/bash-completion/bash-completion ]] && \
				. /usr/share/bash-completion/bash-completion

shopt -s autocd
shopt -s cdspell
